mdapi/objects/ltng_UrlHackBase__c.object
<CustomObject>
    <description>Base / Parent object to use when demoing the URL Hack Replacement.</description>
    <label>URL Hack Base</label>
    <nameField>
        <label>Url Hack Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>URL Hack Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CustomDescription__c</fullName>
        <inlineHelpText>Description of this object</inlineHelpText>
        <label>Custom Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SampleCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SampleDate__c</fullName>
        <label>Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SampleNumber__c</fullName>
        <label>Sample Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SamplePicklist__c</fullName>
        <label>Sample Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/ltng_URLHackChild__c.object
<CustomObject>
    <description>Child object created using the URL Hack</description>
    <label>URL Hack Child</label>
    <nameField>
        <label>URL Hack Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>URL Hack Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CustomDescription__c</fullName>
        <label>Custom Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SampleCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SampleDate__c</fullName>
        <label>Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SampleNumber__c</fullName>
        <label>Sample Number</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SamplePicklist__c</fullName>
        <label>Sample Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Extended</fullName>
        <active>true</active>
        <description>Extended version of the URL Hack Record</description>
        <label>Extended</label>
    </recordTypes>
</CustomObject>

mdapi/objects/ltng_URLHackCustomMetadata__mdt.object
<CustomObject>
    <description>Example metadata used when performing a URL Hack</description>
    <label>URL Hack Custom Metadata</label>
    <pluralLabel>URL Hack Custom Metadata</pluralLabel>
    <fields>
        <fullName>MetadataValue__c</fullName>
        <defaultValue>"Value from Custom Metadata"</defaultValue>
        <inlineHelpText>Value to be used in URL Hack</inlineHelpText>
        <label>Metadata Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/objects/ltng_URLHackCustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Example custom setting used in the URL Hack.</description>
    <label>URL Hack Custom Setting</label>
</CustomObject>

dx/force-app/main/default/classes/ltng_UrlHackListButtonCtrl.cls
/**
 * Controller for VisualForce page that performs a 'URL Hack' from a List Button.
 * @class ltng_UrlHackListButtonCtrl
 **/
public class ltng_UrlHackListButtonCtrl {
    
    //-- store properties for all data to be available for defaulting.
    
    /** Current user's info **/
    public String currentUserLastName {get;set;}
    
    /** RecordType Id for the new Child **/
    public String recordTypeId {get;set;}
    
    /** Record with info to pass in defaulted properties **/
    public ltng_UrlHackBase__c baseInfo {get;set;}
    
    /** Custom Setting info to pass in defaulted properties **/ 
    public ltng_UrlHackCustomSetting__c customSettingInfo {get;set;}
    
    /** Custom Metadata info to pass in defaulted properties **/ 
    public ltng_UrlHackCustomMetadata__mdt customMetadataInfo {get;set;}
    
    /** Constructor **/
    public ltng_UrlHackListButtonCtrl( ApexPages.StandardSetController controller ){
        //-- get the context from the originating Parent Account
        Map<String,String> params = new Map<String,String>();
        params = ApexPages.currentPage().getParameters();
		
        //-- get the ID of the Base Record to pull from
        String baseRecordId = params.get('id');
        
        //-- UPDATE THE LINES BELOW
        //--	-	-	-	-	-	-	-	-	-	-	-
        
        //-- retrieve all the info you need to default
        //-- recordTypeIds are needed if there are multiple
        
        try {
            this.recordTypeId = [
                SELECT Id, DeveloperName, Name, SObjectType
                FROM RecordType
                WHERE SObjectType = 'ltng_URLHackChild__c'
                AND DeveloperName = 'Extended'
            ].Id;
        } catch(Exception err){
            System.debug('unable to find record type ID');
            System.debug(err);
        }
        
        //-- fetch the user information
        this.currentUserLastName = UserInfo.getLastName();
        
        //-- fetch the base object info
        try {
            this.baseInfo = [SELECT Id, Name, CustomDescription__c,
                	SampleCheckbox__c, SampleDate__c, SampleNumber__c,
                	SamplePicklist__c
                FROM ltng_UrlHackBase__c
                WHERE Id = :baseRecordId
                LIMIT 1
            ];
        } catch(Exception err){
            System.debug('exception when finding contact');
            System.debug(err);
        }
                
        //-- fetch custom Settings
        try {
            this.customSettingInfo = ltng_UrlHackCustomSetting__c.getInstance();
        } catch(Exception err){
            System.debug('No Opportunity Settings instance found');
            System.debug(err);
        }
        
        //-- fetch custom metadata
        try {
            this.customMetadataInfo = [
                SELECT id, MetadataValue__c, QualifiedAPIName
                FROM ltng_URLHackCustomMetadata__mdt
                WHERE QualifiedApiName = 'ExampleCustomMetadata'
                LIMIT 1
            ];
        } catch(Exception err){
            System.debug('No custom metadata found');
            System.debug(err);
        }
        
        //-- optionally get information from custom metadata
    }
}