mdapi/objects/ltng_UrlHackBase__c.object
<CustomObject>
    <description>Base / Parent object to use when demoing the URL Hack Replacement.</description>
    <label>URL Hack Base</label>
    <nameField>
        <label>Url Hack Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>URL Hack Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CustomDescription__c</fullName>
        <inlineHelpText>Description of this object</inlineHelpText>
        <label>Custom Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SampleCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SampleDate__c</fullName>
        <label>Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SampleNumber__c</fullName>
        <label>Sample Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SamplePicklist__c</fullName>
        <label>Sample Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/ltng_URLHackChild__c.object
<CustomObject>
    <description>Child object created using the URL Hack</description>
    <label>URL Hack Child</label>
    <nameField>
        <label>URL Hack Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>URL Hack Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CustomDescription__c</fullName>
        <label>Custom Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SampleCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SampleDate__c</fullName>
        <label>Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SampleNumber__c</fullName>
        <label>Sample Number</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SamplePicklist__c</fullName>
        <label>Sample Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Extended</fullName>
        <active>true</active>
        <description>Extended version of the URL Hack Record</description>
        <label>Extended</label>
    </recordTypes>
</CustomObject>

mdapi/objects/ltng_URLHackCustomMetadata__mdt.object
<CustomObject>
    <description>Example metadata used when performing a URL Hack</description>
    <label>URL Hack Custom Metadata</label>
    <pluralLabel>URL Hack Custom Metadata</pluralLabel>
    <fields>
        <fullName>MetadataValue__c</fullName>
        <defaultValue>"Value from Custom Metadata"</defaultValue>
        <inlineHelpText>Value to be used in URL Hack</inlineHelpText>
        <label>Metadata Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/objects/ltng_URLHackCustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Example custom setting used in the URL Hack.</description>
    <label>URL Hack Custom Setting</label>
</CustomObject>

dx/force-app/main/default/classes/ltng_URLHackComponentCtrl.cls
/**
 * Controller for for the ltng_URLHackComponent Lightning Component.
 */
public with sharing class ltng_URLHackComponentCtrl {
    
    /**
     * Determines the list of default values to use
     * when creating the child record.
     * @param baseRecordId (Id)
     * @return UrlHackDefaultValues - custom object that contains everything it needs.
     */
    @AuraEnabled
    public static UrlHackDefaultValues getUrlHackDefaultValues(Id baseRecordId){

        UrlHackDefaultValues results = new UrlHackDefaultValues();


        //--	-	-	-	-	-	-	-	-	-	-	-
        //-- UPDATE THE LINES BELOW
        //--	-	-	-	-	-	-	-	-	-	-	-

        //-- get the base object info
        try {
            results.baseInfo = [
                SELECT Id, Name, CustomDescription__c,
                    SampleCheckbox__c, SampleDate__c, SampleNumber__c,
                    SamplePicklist__c
                FROM ltng_UrlHackBase__c
                WHERE Id = :baseRecordId
                LIMIT 1
            ];
        } catch(Exception err){
            System.debug('exception when fetching the base record');
            System.debug(err);
        }

        //-- get the record type that the child should be
        //-- Schema.SObjectType.SOBJECT_NAME.getRecordTypeInfosByName().get('RECORD_TYPE_NAME').getRecordTypeId();

        results.childRecordTypeId = Schema.SObjectType.ltng_UrlHackChild__c
            .getRecordTypeInfosByName().get('Extended').getRecordTypeId();
        
        //-- get the current user's last name;
        results.currentUserLastName = UserInfo.getLastName();

        //-- fetch custom Settings
        try {
            results.customSettingInfo = ltng_UrlHackCustomSetting__c.getInstance();
        } catch(Exception err){
            System.debug('No Opportunity Settings instance found');
            System.debug(err);
        }
        
        //-- fetch custom metadata
        try {
            results.customMetadataInfo = [
                SELECT id, MetadataValue__c, QualifiedAPIName
                FROM ltng_URLHackCustomMetadata__mdt
                WHERE QualifiedApiName = 'ExampleCustomMetadata'
                LIMIT 1
            ];
        } catch(Exception err){
            System.debug('No custom metadata found');
            System.debug(err);
        }
        //--	-	-	-	-	-	-	-	-	-	-	-
        //-- UPDATE THE LINES ABOVE
        //--	-	-	-	-	-	-	-	-	-	-	-

        return results;
    }

    public class UrlHackDefaultValues {

        //--	-	-	-	-	-	-	-	-	-	-	-
        //-- UPDATE THE LINES BELOW
        //--	-	-	-	-	-	-	-	-	-	-	-
        /** base info you want to return **/
        @AuraEnabled
        public ltng_URLHackBase__c baseInfo;
        
        /** record type id for the new child **/
        @AuraEnabled
        public String childRecordTypeId;

        /** last name of the current user **/
        @AuraEnabled
        public String currentUserLastName;

        /** custom setting values **/
        @AuraEnabled
        public ltng_UrlHackCustomSetting__c customSettingInfo;

        /** custom metadata values **/
        @AuraEnabled
        public ltng_URLHackCustomMetadata__mdt customMetadataInfo;
        //--	-	-	-	-	-	-	-	-	-	-	-
        //-- UPDATE THE LINES ABOVE
        //--	-	-	-	-	-	-	-	-	-	-	-
    }    
}